### ISSUE TITLE
git (and crew) broken after upgrade: can't load libcharset.so.1

### ISSUE THREAD

**Issue by nealmcb** [skycocker/chromebrew#3305]
## Description

My git is now broken:

    $ git --version
    git: error while loading shared libraries: libcharset.so.1: cannot open shared object file: No such file or directory

Unfortunately, that also breaks many crew commands!

It broke after an upgrade to git version 2.21.0.

```shell
crew upgrade git
```

## Versions and system information
chromebrew: `crew --version`
1.2.4

ChromeOS: `cat /etc/lsb-release`
CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=5563251
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={C166AF52-7EE9-4F08-AAA7-B4B895A9F336}
CHROMEOS_RELEASE_BOARD=caroline-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=118
CHROMEOS_RELEASE_BUILDER_PATH=caroline-release/R74-11895.118.0
CHROMEOS_RELEASE_BUILD_NUMBER=11895
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=74
CHROMEOS_RELEASE_DESCRIPTION=11895.118.0 (Official Build) stable-channel caroline 
CHROMEOS_RELEASE_KEYSET=mp
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11895.118.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=11895.118.0
Model: YOUR MODEL HERE
Samsung Pro

Architecture: `uname -m`
x86_64

## Addtional information

What I think needs to be done:
- [ ] explain how to fix broken crew installation
- [ ] fix upgrades to git, and perhaps even warn that they can break crew like this.

**Comment by uberhacker** [comment]
@nealmcb: It appears you need to install libiconv which is a dependency of git.  Does `crew install libiconv` fix git?

**Comment by uberhacker** [comment]
I think the real bug is `crew upgrade` doesn't check for new dependencies on a package update.  It happens so rarely, it might not be worth the effort to fix, actually.  We could put a new Q & A entry in the [FAQ](https://github.com/skycocker/chromebrew/wiki/FAQ).

**Comment by nealmcb** [comment]
@uberhacker Yes, git seems to work now. Thanks!

In the case of git, at least, since it is important for crew itself, more hand-holding on upgrade would be especially valuable. I'm surprised this hasn't come up before. And I don't see libiconv listed for git, though it is in core now I guess.
When did it become required?

**Comment by uberhacker** [comment]
You are right!  We need to add `depends_on 'libiconv'` to git.  The first version that required it was 2.19.0.  I'll try to remember to include the dependency on the next upgrade.

**Comment by LK4D4** [comment]
Looks like it also breaks installation.

**Comment by uberhacker** [comment]
@LK4D4: Can you please indicate the error you receive?  I have reinstalled fresh many times without an issue.

**Comment by LK4D4** [comment]
@uberhacker sorry for misunderstanding, I was trying to install it in crostini container which apparently I'm not supposed to do :)
Error was same as in top post.

**Comment by uberhacker** [comment]
No worries.  Not to make it sound more confusing but ChromeOS has decided to allow crostini container access from the terminal.  See https://www.chromestory.com/2019/06/crostini-terminal-to-move-to-chrome-terminal/.

**Comment by lupulin** [comment]
I'm trying to install chromebrew and I'm having the same error. 

I added `depends_on 'libiconv'` to git.rb. But, I still get the error:

```
Verifying libssh2...
libssh2-1.8.1-chromeos-x86_64.tar.xz: OK
Extracting libssh2 (this may take a while)...
Installing libssh2 (this may take a while)...
Adding new information on libssh2 to device.json...
git: error while loading shared libraries: libcharset.so.1: cannot open shared object file: No such file or directory
```

**Comment by jayvdb** [comment]
I also encountered this when doing a fresh install on an empty image.

**Comment by uberhacker** [comment]
Just to clarify, this error happens when attempting to install Chromebrew in a Crostini container and not in Crosh on bare metal?  If so, I cannot think of a reason you would ever what to do this. :)

**Comment by jayvdb** [comment]
https://gitlab.com/jayvdb/package_manager/-/jobs/242587574

Using docker `brunux/chromeos`

I want to support `crew` package manager with our [`BrewRequirement`](https://gitlab.com/coala/package_manager/blob/master/dependency_management/requirements/BrewRequirement.py) class.

**Comment by nealmcb** [comment]
@jayvdb Can you lead us thru the use case some more: for who, on what, wanting what?
This is part of coala? What is that - I see no README or the like at https://gitlab.com/coala

**Comment by jayvdb** [comment]
https://gitlab.com/coala/package_manager is where you will find the README

The org links to https://coala.io ; the main repos are https://github.com/coala/coala and https://github.com/coala/coala-bears

I want the installer to work.  Quite simple really.

**Comment by jayvdb** [comment]
It would be a good idea to add some CI to this project.

**Comment by uberhacker** [comment]
@jayvdb: Easier said than done.  This has been considered but we need smart people like you to help make it happen. :)

**Comment by jayvdb** [comment]
Catch 22 at the moment - this bug needs to be fixed.

**Comment by uberhacker** [comment]
After a bit of analysis, the issue is the install (and subsequently core) has added libiconv as a dependency to git but the git package did not include this dependency which caused upgrades to fail.  PR #3360 should fix this from happening in the future.

**Comment by uberhacker** [comment]
Fixed in #3360.

**Comment by jayvdb** [comment]
I am pretty sure that didnt solve it.

The iconv package doesnt include libcharset.so.1.  Instead it contains libcharset.so and libcharset.so.1.0.0 .  Adding another symlink in the iconv package should fix it , or the install.sh could add this.

**Comment by uberhacker** [comment]
@jayvdb: How so?
```
$ crew whatprovides libcharset
libiconv: /usr/local/include/libcharset.h
libiconv: /usr/local/lib/libcharset.a
libiconv: /usr/local/lib/libcharset.la
libiconv: /usr/local/lib/libcharset.so
libiconv: /usr/local/lib/libcharset.so.1
libiconv: /usr/local/lib/libcharset.so.1.0.0

Total found: 6
```
