### ISSUE TITLE
[wayland] Unable to build from source

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#4985]
```
config.status: linking protocol/wayland.dtd to src/wayland.dtd.embed
config.status: executing depfiles commands
config.status: executing libtool commands
  CC       src/wayland_scanner-scanner.o
  CPPAS    src/wayland_scanner-dtddata.o
  CC       src/libwayland_util_la-wayland-util.lo
In file included from /usr/local/include/libxml2/libxml/parser.h:810,
                 from src/scanner.c:42:
/usr/local/include/libxml2/libxml/encoding.h:28:10: fatal error: iconv.h: No such file or directory
   28 | #include <iconv.h>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:1963: src/wayland_scanner-scanner.o] Error 1
make: *** Waiting for unfinished jobs....
wayland failed to install: `make V=0 -j4` exited with 2
```

**Comment by satmandu** [comment]
A reinstall of glibc should fix the problem, I think...

**Comment by uberhacker** [comment]
That fixed it, however, since we still have a lacking dependency resolver, we'll need new binaries for `wayland` and `wayland_protocols` to allow users to `crew upgrade`.  We should have binaries for everything anyway.

**Comment by satmandu** [comment]
Yeah I noticed that last night for Wayland protocols, but that install from
source is very very quick.
