### ISSUE TITLE
Fresh install fails

### ISSUE THREAD

**Issue by uberhacker** [skycocker/chromebrew#5842]
```
Downloading curl...
############################################################################################################################################## 100.0%
Verifying curl...
curl-7.77.0-chromeos-x86_64.tpxz: OK
Extracting curl (this may take a while)...
Installing curl (this may take a while)...
Adding new information on curl to device.json...
Downloading git...
curl: error while loading shared libraries: libssh.so.4: cannot open shared object file: No such file or directory
````
Looks like a curl dependency is missing and curl is not fully static.

**Comment by satmandu** [comment]
I think this is now fixed. I redid the curl build to exclude libssh, which is giving problems.

**Comment by exoad** [comment]
I tried deleting Crew with `sudo rm -r /usr/local/*` then rerunning the install command, the error still persists.

**Comment by uberhacker** [comment]
@satmandu: The install is still broken.  I'm going to mark this high priority.  Did you fix in a pending PR?  If so, that doesn't help until it gets merged into master. :)

**Comment by satmandu** [comment]
I meant fixed in a PR... :/

Now testing install.sh...

**Comment by uberhacker** [comment]
git is still broken on i686:
```
Downloading git...
######################################################################## 100.0%
Verifying git...
git-2.32.0-chromeos-i686.tpxz: OK
Extracting git (this may take a while)...
Installing git (this may take a while)...
Adding new information on git to device.json...
Downloading icu4c...
######################################################################## 100.0%
Verifying icu4c...
icu4c-69.1-chromeos-i686.tpxz: OK
Extracting icu4c (this may take a while)...
Installing icu4c (this may take a while)...
Adding new information on icu4c to device.json...
‘/usr/local/bin/crew’ -> ‘../lib/crew/bin/crew’
bash: line 200: 18415 Segmentation fault      (core dumped) git init
```

**Comment by satmandu** [comment]
Also issues on x86_64 with segfaults... :/
