### ISSUE TITLE
Can't install nodejs

### ISSUE THREAD

**Issue by ruoyu0088** [skycocker/chromebrew#84]
here is the error message:

`Checksum mismatch :/ try again`

it seems that the checksum in http://nodejs.org/dist/v0.12.0/SHASUMS.txt is not the same as the checksum in nodejs.rb.

**Comment by misfirerm** [comment]
Same thing here. All dependencies install ok, but not nodejs:
==============================================

Found nodejs, version 0.12.0
No precompiled binary available for your platform, downloading source...
WARNING: timestamping does nothing in combination with -O. See the manual
for details.

--2015-07-19 08:12:27--  http://nodejs.org/dist/v0.12.0/node-v0.12.0.tar.gz
Resolving nodejs.org... 165.225.133.150
Connecting to nodejs.org|165.225.133.150|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19096897 (18M) [application/octet-stream]
--2015-07-19 08:12:28--  http://nodejs.org/dist/v0.12.0/node-v0.12.0.tar.gz
Reusing existing connection to nodejs.org:80.
HTTP request sent, awaiting response... 200 OK
Length: 19096897 (18M) [application/octet-stream]
Saving to: 'node-v0.12.0.tar.gz'

node-v0.12.0.tar.gz            100%[=====================================================>]  18.21M  5.93MB/s   in 3.1s   

2015-07-19 08:12:31 (5.93 MB/s) - 'node-v0.12.0.tar.gz' saved [19096897/19096897]

Checksum mismatch :/ try again

**Comment by Tivoli** [comment]
This issue should be fixed @skycocker, if someone else wants to verify.

**Comment by thedamian** [comment]
There's a new change that fixes this.

Just run:
crew update
then crew upgrade nodejs
(or crew install nodejs if you haven't installed it yet)

You should be fine after that.

Still not working? Simply update your /usr/local/lib/crew/packages/nodejs.rb with the contents on this page:
https://raw.githubusercontent.com/skycocker/chromebrew/master/packages/nodejs.rb

**Comment by thedamian** [comment]
I suggest closing this issue

**Comment by skycocker** [comment]
let's close this for now, if someone comes up with still broken nodejs, he should be able to find this issue quickly and reopen it.
